# Generated by Django 5.2 on 2025-04-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablesize',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogram'), ('pc', 'Piece'), ('g', 'Gram'), ('ltr', 'Liter'), ('ml', 'Milliliter'), ('m', 'Meter'), ('cm', 'Centimeter'), ('mm', 'Millimeter')], max_length=10),
        ),
    ]
