# Generated by Django 5.2 on 2025-04-24 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_availablesize_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='background_color',
            field=models.CharField(choices=[('danger', 'Red'), ('success', 'Green'), ('info', 'Blue'), ('warning', 'Yellow'), ('primary', 'Indigo'), ('secondary', 'Gray'), ('light', 'Light Gray'), ('dark', 'Black')], default='success', max_length=10),
        ),
    ]
