# Generated by Django 5.2.1 on 2025-05-31 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='team',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
