# Generated by Django 5.2.1 on 2025-06-02 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('poster', 'Poster'), ('video', 'Video'), ('creative_video', 'Creative Video'), ('package_design', 'Package Design')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/')),
                ('video', models.FileField(blank=True, null=True, upload_to='works/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
