# Generated by Django 5.2.1 on 2025-06-02 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('posters', 'Posters'), ('videos', 'Videos'), ('creative_videos', 'Creative Videos'), ('package_designs', 'Package Designs'), ('logos', 'Logos'), ('Web_designs', 'Web Design'), ('brochures', 'Brochures')], max_length=20),
        ),
    ]
