# Generated by Django 5.2.1 on 2025-06-02 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0002_alter_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('cat1', 'Posters'), ('cat2', 'Videos'), ('cat3', 'Creative Videos'), ('cat4', 'Package Designs'), ('cat5', 'Logos'), ('cat6', 'Web Design'), ('cat7', 'Brochures')], max_length=20),
        ),
    ]
