# Generated by Django 5.2.1 on 2025-06-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_alter_work_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='works/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='works/posters/'),
        ),
    ]
