# Generated by Django 5.2.1 on 2025-06-02 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_work_thumbnail_alter_work_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='category',
            field=models.CharField(choices=[('posters', 'Posters'), ('videos', 'Videos'), ('creative_videos', 'Creative Videos'), ('package_designs', 'Package Designs'), ('logog', 'Logos'), ('web_design', 'Web Design'), ('brochures', 'Brochures')], max_length=20),
        ),
    ]
